refactor!: big rewrite
1. rewrite how to handle options
2. move result directory existence check & creation before the creation of temporary files (hashing script & mapper output)
3. `timer` function: use `date` time string formatting and handle different version of date (Linux, macOS & FreeBSD)
4. `timer` function: `timer` will return elapsed time, and time difference when given a start time.
5. `timer` function: use `$SECONDS`
6. show temporary hashing script creation information
7. trap `clean_up` when exiting

diff --git a/lmr b/lmr
--- a/lmr
+++ b/lmr
@@ -3,21 +3,16 @@
 function usage() { echo "Usage: $0 [-k] <BLOCKSIZE> <NUM_HASHING_SEGS> <MAPPER> <REDUCER> <OUTPUT_DIR>" 1>&2; exit 1; }
 
 keep_mapper_out=false
-while getopts "k" o; do
-    case "${o}" in
-        k)
-            keep_mapper_out=true
-            ;;
-        *)
-            usage
-            ;;
+while getopts ":k" OPTION
+do
+    case $OPTION in
+        k) keep_mapper_out=true;;
+        ?) usage;;
     esac
 done
 shift $((OPTIND-1))
 
-if [ "$#" -ne 5 ]; then
-    usage
-fi
+[ "$#" -ne 5 ] && usage
 
 BLOCKSIZE="$1"
 NUM_HASHING_SEGS="$2"
@@ -25,32 +20,24 @@ MAPPER="$3"
 REDUCER="$4"
 OUTPUT_DIR="$5"
 
+mkdir "$OUTPUT_DIR" || exit 1
+
 function timer()
 {
-    if [[ $# -eq 0 ]]; then
-        echo $(date '+%s')
-    else
-        local  stime=$1
-        etime=$(date '+%s')
-
-        if [[ -z "$stime" ]]; then stime=$etime; fi
-
-        dt=$((etime - stime))
-        ds=$((dt % 60))
-        dm=$(((dt / 60) % 60))
-        dh=$((dt / 3600))
-        printf '%d:%02d:%02d' $dh $dm $ds
-    fi
+    local stime=$1
+    [[ -z $stime ]] && stime=$START_TIME
+    [[ -z $stime ]] && stime=0
+    dt=$((SECONDS - stime))
+    date -d@$dt -u +%H:%M:%S 2>/dev/null || date -u -r $dt +%T
 }
 
-START_TIME=$(timer)
-
 HASHING_SCRIPT=`mktemp hashing.py.XXXX`
-echo hashing script $HASHING_SCRIPT
-# trap 'rm -r "$HASHING_SCRIPT"' SIGHUP SIGINT SIGTERM
+{
+    echo $' \e[1;32m>>>\e[m Temporary mapper hashing script created: \e[1;32m'$HASHING_SCRIPT$'\e[m'
+}>&2
 TEMPDIR=`mktemp -d mapper_tmp.XXXX`
 {
-    echo $' \e[1;32m>>>\e[m' Temporary output directory for mapper created: $'\e[1;32m'$TEMPDIR$'\e[m'
+    echo $' \e[1;32m>>>\e[m Temporary mapper output directory created: \e[1;32m'$TEMPDIR$'\e[m'
 }>&2
 
 function clean_up() {
@@ -60,10 +47,14 @@ function clean_up() {
         rm -r "$TEMPDIR" &&
         echo  $' \e[1;32m>>>\e[m' Temporary directory deleted: $'\e[1;32m'"$TEMPDIR"$'\e[m' ||
         echo  $' \e[1;31m*\e[m' Failed to delete temporary directoy: $'\e[1;32m'"$TEMPDIR"$'\e[m'
+    else
+        echo  $' \e[1;33m*\e[m' Mapper output directory: $'\e[1;32m'"$TEMPDIR"$'\e[m'
     fi
-    rm "$HASHING_SCRIPT"
+    rm "$HASHING_SCRIPT" &&
+    echo  $' \e[1;32m>>>\e[m' Temporary hashing script deleted: $'\e[1;32m'"$HASHING_SCRIPT"$'\e[m' ||
+    echo  $' \e[1;31m*\e[m' Failed to delete hashing script: $'\e[1;32m'"$HASHING_SCRIPT"$'\e[m'
 } >&2
-trap 'clean_up; exit' SIGHUP SIGINT SIGTERM
+trap 'clean_up; exit' SIGHUP SIGINT SIGTERM EXIT
 
 cat <<EOF > "${HASHING_SCRIPT}"
 #!/usr/bin/env python
@@ -72,14 +63,11 @@ import sys, os, fileinput
 
 N_REDUCER, MAPPER_ID, BASE_DIR  = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
 
-# print(MAPPER_ID, ' ', file = sys.stderr, end = '')
-# print(MAPPER_ID, end = ' ')
-
 def outfile(seg_id):
-    segdir = '{}/reducer-{:02}'.format(BASE_DIR, seg_id)
+    segdir = os.path.join(BASE_DIR, f"reducer-{seg_id:02}")
     try: os.makedirs(segdir)
     except OSError : pass
-    return open('{}/mapper-{:02}'.format( segdir, MAPPER_ID ), 'w')
+    return open(f"{segdir}/mapper-{MAPPER_ID:02}", 'w')
 
 seg_file = [outfile(seg_id) for seg_id in range(N_REDUCER)]
 
@@ -90,23 +78,16 @@ fileinput.close()
 for seg_id in range(N_REDUCER): seg_file[seg_id].close()
 EOF
 
+START_TIME=timer
 
-mkdir "$5" || exit 1
-echo  $' \e[1;33m>>>\e[m' Mappers running...
+echo $' \e[1;33m>>>\e[m' Mappers running... $'\e[1;33m'$(timer START_TIME)$'\e[m'
 echo
 parallel --pipe --block "${BLOCKSIZE}" --ungroup "echo -n $'\e[s\e[F\e[2K           #{#}\e[u'; ${MAPPER} | PYTHONHASHSEED=0 python $HASHING_SCRIPT ${NUM_HASHING_SEGS} {#} $TEMPDIR" # pipe to here
-# parallel --pipe --block "$1" "$3 | python $HASHING_SCRIPT $2 1 $TEMPDIR" # io.open line buffering
-# echo $TEMPDIR
+
+echo -n $' \e[1;33m>>>\e[m' Reducer running... $'\e[1;33m'$(timer START_TIME)$'\e[m'
 parallel --ungroup "sort -k 1,1 -t $'\t' {}/* | ${REDUCER} > '${OUTPUT_DIR}/{/.}'"  ::: "${TEMPDIR}"/*
-echo  $' \e[1;33m>>>\e[m' Reducer running. Temporary input directory: $'\e[1;32m'"$TEMPDIR"$'\e[m'
 {
-    clean_up
     echo
-    if [ $keep_mapper_out = true ] ; then
-        echo  $' \e[1;33m*\e[m' Mapper output directory: $'\e[1;32m'"$TEMPDIR"$'\e[m'
-    fi
-
     echo  $' \e[1;33m*\e[m' Output directory: $'\e[1;32m'"$OUTPUT_DIR"$'\e[m'
-    echo  $' \e[1;33m*\e[m' Elasped time: $'\e[1;32m'$(timer $START_TIME)$'\e[m'
-
+    echo  $' \e[1;33m*\e[m' Elasped time: $'\e[1;32m'$(timer START_TIME)$'\e[m'
 } >&2
