option to keep mapper output. usage message

diff --git a/localmapreduce b/localmapreduce
--- a/localmapreduce
+++ b/localmapreduce
@@ -1,5 +1,24 @@
 #!/bin/bash
 
+function usage() { echo "Usage: $0 [-k] <BLOCKSIZE> <NUM_HASHING_SEGS> <MAPPER> <REDUCER> <OUTPUT_DIR>" 1>&2; exit 1; }
+
+keep_mapper_out=false
+while getopts "k" o; do
+    case "${o}" in
+        k)
+            keep_mapper_out=true
+            ;;
+        *)
+            usage
+            ;;
+    esac
+done
+shift $((OPTIND-1))
+
+if [ "$#" -ne 5 ]; then
+    usage
+fi
+   
 BLOCKSIZE="$1"
 NUM_HASHING_SEGS="$2"
 MAPPER="$3"
@@ -37,7 +56,11 @@ TEMPDIR=`mktemp -d mapper_tmp.XXXX`
 function clean_up() {
     echo $' \e[1;32m>>>\e[m Cleaning...'
     sleep 1
-    rm -r "$TEMPDIR" && echo  $' \e[1;32m>>>\e[m' Temporary directory deleted: $'\e[1;32m'"$TEMPDIR"$'\e[m' || echo  $' \e[1;31m*\e[m' Failed to delete temporary directoy: $'\e[1;32m'"$TEMPDIR"$'\e[m'
+    if [ $keep_mapper_out = false ] ; then
+        rm -r "$TEMPDIR" &&
+        echo  $' \e[1;32m>>>\e[m' Temporary directory deleted: $'\e[1;32m'"$TEMPDIR"$'\e[m' ||
+        echo  $' \e[1;31m*\e[m' Failed to delete temporary directoy: $'\e[1;32m'"$TEMPDIR"$'\e[m'
+    fi
     rm "$HASHING_SCRIPT"
 } >&2
 trap 'clean_up; exit' SIGHUP SIGINT SIGTERM 
@@ -51,6 +74,7 @@ def tokens(str1): return re.findall('[a-z]+', str1.lower())
 N_REDUCER, MAPPER_ID, BASE_DIR  = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
 
 # print(MAPPER_ID, ' ', file = sys.stderr, end = '')
+# print(MAPPER_ID, end = ' ')
 
 import base64
 def outfile(seg_id):
@@ -73,8 +97,8 @@ EOF
 
 mkdir "$5" || exit 1
 echo  $' \e[1;33m>>>\e[m' Mappers running...
-
-parallel --pipe --block "${BLOCKSIZE}"  --ungroup   "${MAPPER}  | python $HASHING_SCRIPT ${NUM_HASHING_SEGS} {#} $TEMPDIR" # pipe to here
+echo 
+parallel --pipe --block "${BLOCKSIZE}"  --ungroup   "echo -n $'\e[s\e[F\e[2K           #{#}\e[u' ; ${MAPPER}  | python $HASHING_SCRIPT ${NUM_HASHING_SEGS} {#} $TEMPDIR " # pipe to here
 # parallel --pipe --block "$1" "$3 | python $HASHING_SCRIPT $2 1 $TEMPDIR" # io.open line buffering
 # echo $TEMPDIR
 parallel   --ungroup "sort -k 1,1 -t $'\t' {}/*  | ${REDUCER} > '${OUTPUT_DIR}/{/.}'"  ::: "${TEMPDIR}"/*
@@ -82,6 +106,10 @@ echo  $' \e[1;33m>>>\e[m' Reducer running. Temporary input directory: $'\e[1;32m
 {
     clean_up
     echo 
+    if [ $keep_mapper_out = true ] ; then
+        echo  $' \e[1;33m*\e[m' Mapper output directory: $'\e[1;32m'"$TEMPDIR"$'\e[m'
+    fi
+    
     echo  $' \e[1;33m*\e[m' Output directory: $'\e[1;32m'"$OUTPUT_DIR"$'\e[m'
     echo  $' \e[1;33m*\e[m' Elasped time: $'\e[1;32m'$(timer $START_TIME)$'\e[m'
     
